- id: doi:10.1101/2025.08.20.671362
  title: Pretraining Improves Prediction of Genomic Datasets Across Species
  authors:
  - "Fangrui Huang\\\x2A"
  - "Yitong Wang\\\x2A"
  - "Janet Song^"
  - "Ashok Cutkosky^"
  publisher: bioRxiv
  date: '2025-08-24'
  link: https://doi.org/g928gh

- id: doi:10.1101/2025.03.31.646366
  title: FOS binding sites are a hub for the evolution of activity-dependent gene
    regulatory programs in human neurons
  authors:
  - "Ava C. Carter\\\x2A"
  - "Gabriel T. Koreman\\\x2A"
  - Jillian E. Petrocelli
  - Josephine E. Robb
  - Evan M. Bushinsky
  - Sara K. Trowbridge
  - David M. Kingsley
  - "Christopher A. Walsh^"
  - "Janet H.T. Song^"
  - "Michael E. Greenberg^"
  publisher: bioRxiv
  date: '2025-04-01'
  link: https://doi.org/g9bg9k

- id: doi:10.1101/2025.03.31.646367
  title: Human-chimpanzee tetraploid system defines mechanisms of species-specific
    neural gene regulation
  authors:
  - "Janet HT Song\\\x2A^"
  - "Ava C Carter\\\x2A"
  - Evan M Bushinsky
  - Samantha G Beck
  - Jillian E Petrocelli
  - Gabriel T Koreman
  - Juliana Babu
  - David M Kingsley
  - "Michael E Greenberg^"
  - "Christopher A Walsh^"
  publisher: bioRxiv
  date: '2025-03-31'
  link: https://doi.org/g9bg9m

- id: doi:10.1101/2025.01.20.634000
  title: Autism-Associated Genes and Neighboring lncRNAs Converge on Key Gene Regulatory
    Networks
  authors:
  - Rebecca Andersen
  - Maya Talukdar
  - Tyler Sakamoto
  - Janet HT Song
  - Xuyu Qian
  - Seungil Lee
  - Ryan N Delgado
  - Sijing Zhao
  - Gwenyth Eichfeld
  - Julia Harms
  - Christopher A Walsh
  publisher: bioRxiv
  date: '2025-01-22'
  link: https://doi.org/g82vdm

- id: doi:10.1016/j.xgen.2024.100609
  title: Rare variation in non-coding regions with evolutionary signatures contributes
    to autism spectrum disorder risk
  authors:
  - "Taehwan Shin\\\x2A"
  - "Janet H.T. Song\\\x2A"
  - Michael Kosicki
  - Connor Kenny
  - Samantha G. Beck
  - Lily Kelley
  - Irene Antony
  - Xuyu Qian
  - Julieta Bonacina
  - Frances Papandile
  - Dilenny Gonzalez
  - Julia Scotellaro
  - Evan M. Bushinsky
  - Rebecca E. Andersen
  - Eduardo Maury
  - Len A. Pennacchio
  - "Ryan N. Doan^"
  - "Christopher A. Walsh^"
  publisher: Cell Genomics
  date: '2024-07-01'
  link: https://doi.org/gt4w44

- id: doi:10.1126/science.ade9516
  title: Comparative transcriptomics reveals human-specific cortical features
  authors:
  - "Nikolas L. Jorstad\\\x2A"
  - "Janet H.T. Song\\\x2A"
  - "David Exposito-Alonso\\\x2A"
  - Hamsini Suresh
  - Nathan Castro-Pacheco
  - Fenna M. Krienen
  - Anna Marie Yanny
  - Jennie Close
  - Emily Gelfand
  - Brian Long
  - Stephanie C. Seeman
  - Kyle J. Travaglini
  - Soumyadeep Basu
  - Marc Beaudin
  - Darren Bertagnolli
  - Megan Crow
  - Song-Lin Ding
  - Jeroen Eggermont
  - Alexandra Glandon
  - Jeff Goldy
  - Katelyn Kiick
  - Thomas Kroes
  - Delissa McMillen
  - Trangthanh Pham
  - Christine Rimorin
  - Kimberly Siletti
  - Saroja Somasundaram
  - Michael Tieu
  - Amy Torkelson
  - Guoping Feng
  - William D. Hopkins
  - "Thomas H\xF6llt"
  - C. Dirk Keene
  - Sten Linnarsson
  - Steven A. McCarroll
  - Boudewijn P. Lelieveldt
  - Chet C. Sherwood
  - Kimberly Smith
  - Christopher A. Walsh
  - Alexander Dobin
  - Jesse Gillis
  - Ed S. Lein
  - "Rebecca D. Hodge^"
  - "Trygve E. Bakken^"
  publisher: Science
  date: '2023-10-13'
  link: https://doi.org/gsvxnr

- id: doi:10.1523/jneurosci.0710-22.2023
  title: Cbln1 directs axon targeting by corticospinal neurons specifically toward
    thoraco-lumbar spinal cord
  authors:
  - Janet H.T. Song
  - Carolin Ruven
  - Payal Patel
  - Frances Ding
  - "Jeffrey D. Macklis^"
  - "Vibhu Sahni^"
  publisher: The Journal of Neuroscience
  date: '2023-02-23'
  link: https://doi.org/gtw9fg

- id: doi:10.1073/pnas.2209964120
  title: TMEM161B regulates cerebral cortical gyration, Sonic Hedgehog signaling,
    and ciliary structure in the developing central nervous system
  authors:
  - Shyam K. Akula
  - Jack H. Marciano
  - Youngshin Lim
  - David Exposito-Alonso
  - Norma K. Hylton
  - Grace H. Hwang
  - Jennifer E. Neil
  - Nicole Dominado
  - Rosie K. Bunton-Stasyshyn
  - Janet H.T. Song
  - Maya Talukdar
  - Aloisia Schmid
  - Lydia Teboul
  - Alisa Mo
  - Taehwan Shin
  - Benjamin Finander
  - Samantha G. Beck
  - Rebecca C. Yeh
  - Aoi Otani
  - Xuyu Qian
  - Ellen M. DeGennaro
  - Fowzan S. Alkuraya
  - Sateesh Maddirevula
  - Gregory D. Cascino
  - Caterina Giannini
  - Lindsay C. Burrage
  - Jill A. Rosenfield
  - Shamika Ketkar
  - Gary D. Clark
  - Carlos Bacino
  - Richard A. Lewis
  - Rosalind A. Segal
  - J. Fernando Bazan
  - Kelly A. Smith
  - Jeffrey A. Golden
  - Ginam Cho
  - Christopher A. Walsh
  publisher: Proceedings of the National Academy of Sciences
  date: '2023-01-20'
  link: https://doi.org/gtw9fh

- id: doi:10.1073/pnas.2117557118
  title: "Genetic studies of human\u2013chimpanzee divergence using stem cell fusions"
  authors:
  - "Janet H.T. Song\\\x2A"
  - "Rachel L. Grant\\\x2A"
  - "Veronica C. Behrens\\\x2A"
  - "Marek Ku\u010Dka"
  - Garrett A. Roberts Kingman
  - Volker Soltys
  - Yingguang Frank Chan
  - David M. Kingsley
  publisher: Proceedings of the National Academy of Sciences
  date: '2021-12-17'
  link: https://doi.org/gnts4x

- id: doi:10.1016/j.celrep.2021.109843
  title: Corticospinal neuron subpopulation-specific developmental genes prospectively
    indicate mature segmentally specific axon projection targeting
  authors:
  - Vibhu Sahni
  - Sara J. Shnider
  - Denis Jabaudon
  - Janet H.T. Song
  - Yasuhiro Itoh
  - Luciano C. Greig
  - Jeffrey D. Macklis
  publisher: Cell Reports
  date: '2021-10-01'
  link: https://doi.org/gtw9fk

- id: doi:10.1016/j.neuron.2021.08.005
  title: Rewiring of human neurodevelopmental gene regulatory programs by human accelerated
    regions
  authors:
  - Kelly M. Girskis
  - Andrew B. Stergachis
  - Ellen M. DeGennaro
  - Ryan N. Doan
  - Xuyu Qian
  - Matthew B. Johnson
  - Peter P. Wang
  - Gabrielle M. Sejourne
  - M. Aurel Nagy
  - Elizabeth A. Pollina
  - "Andr\xE9 M.M. Sousa"
  - Taehwan Shin
  - Connor J. Kenny
  - Julia L. Scotellaro
  - Brian M. Debo
  - Dilenny M. Gonzalez
  - Lariza M. Rento
  - Rebecca C. Yeh
  - Janet H.T. Song
  - Marc Beaudin
  - Jean Fan
  - Peter V. Kharchenko
  - Nenad Sestan
  - Michael E. Greenberg
  - Christopher A. Walsh
  publisher: Neuron
  date: '2021-10-01'
  link: https://doi.org/gtw7

- id: doi:10.1093/biolre/ioab068
  title: "PRG2 and AQPEP are misexpressed in fetal membranes in placenta previa and percreta"
  authors:
  - Elisa T. Zhang
  - Roberta L. Hannibal
  - Keyla M. Badillo Rivera
  - Janet H.T. Song
  - Kelly McGowan
  - Xiaowei Zhu
  - Gudrun Meinhardt
  - "Martin Kn\xF6fler"
  - "J\xFCrgen Pollheimer"
  - Alexander E. Urban
  - Ann K. Folkins
  - Deirdre J. Lyell
  - Julie C. Baker
  publisher: Biology of Reproduction
  date: '2021-05-12'
  link: https://doi.org/gtw9fm

- id: doi:10.1016/j.ajhg.2018.07.011
  title: Characterization of a human-specific tandem repeat associated with bipolar disorder and schizophrenia
  authors:
  - "Janet H.T. Song\\\x2A"
  - "Craig B. Lowe\\\x2A"
  - David M. Kingsley
  publisher: The American Journal of Human Genetics
  date: '2018-09-01'
  link: https://doi.org/gd9r73

- id: doi:10.2147/ndt.s13405
  title: 'Brain volumetric measures in alcoholics: A comparison of two segmentation
    methods'
  authors:
  - Marlene Oscar Berman
  - Janet Song
  publisher: Neuropsychiatric Disease and Treatment
  date: '2011-02-01'
  link: https://doi.org/bs636b

- id: doi:10.1196/annals.1448.019
  title: "Removal of High\u2010Molecular\u2010Weight DNA by Carboxylated Magnetic\
    \ Beads Enhances the Detection of Mutated <i>K\u2010ras</i> DNA in Urine"
  authors:
  - "Ying\u2010Hsiu Su"
  - Janet Song
  - Zhili Wang
  - "Xiao\u2010He Wang"
  - Mengjun Wang
  - Dean E. Brenner
  - Timothy M. Block
  publisher: Annals of the New York Academy of Sciences
  date: '2008-08-01'
  link: https://doi.org/fcbq43

- id: doi:10.1101/2023.09.19.23295780
  remove: true

- id: doi:10.1101/2022.09.19.508480
  remove: true

